{% set version = "4.1.5" %}
{% set ver_maj_min_str = "-".join(version.split(".")[:2]) %}

package:
  name: zeromq
  version: {{ version }}

source:
  fn: zeromq-{{ version }}.tar.gz
  url: https://github.com/zeromq/zeromq{{ ver_maj_min_str }}/archive/v{{ version }}.tar.gz
  sha256: 5a993dcc330e63610fd74a6701b83b020aa5aedf22a98fea01eac93c72ff0b78
  patches:
    # Patch to avoid failing tests on Mac. See issues for details.
    # https://github.com/zeromq/libzmq/issues/1509
    # https://github.com/zeromq/libzmq/issues/1878
    # https://github.com/zeromq/libzmq/issues/1464
    - Makefile.am.mac.patch    # [osx]
    # Patch to avoid a failing test on Linux. See issue for details.
    # https://github.com/zeromq/libzmq/issues/1462
    - Makefile.am.linux.patch  # [linux]

build:
  number: 0
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - toolchain
    - automake        # [unix]
    - autoconf        # [unix]
    - libtool         # [unix]
    - pkg-config      # [unix]
    - libsodium       # [unix]
    - python          # [win]
    - cmake           # [win]
    - vs2015_runtime  # [win and py35]

  run:
    - libsodium   # [unix]
    - vs2015_runtime  # [win and py35]

test:
  commands:
    - test -f ${PREFIX}/lib/libzmq.a           # [unix]
    - test -f ${PREFIX}/lib/libzmq.dylib       # [osx]
    - test -f ${PREFIX}/lib/libzmq.so          # [linux]
  requires:
    - python 2.7.*  # [win and py27]
    - python 3.4.*  # [win and py34]
    - python 3.5.*  # [win and py35]

about:
  home: http://zeromq.org
  license: LGPL 3
  summary: A high-performance asynchronous messaging library.

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
