{% set name = "zeromq" %}
{% set version = "4.2.1" %}
{% set sha256 = "27d1e82a099228ee85a7ddb2260f40830212402c605a4a10b5e5498a7e0e9d03" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zeromq/libzmq/releases/download/v{{ version }}/zeromq-{{ version }}.tar.gz

  sha256: {{ sha256 }}
  patches:
    - cmake-install.patch

build:
  skip: true      # [win]
  number: 0

requirements:
  build:
    - cmake
    - libsodium   # [unix]


  run:
    - libsodium   # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/libzmq.a         # [unix]
    - test -f ${PREFIX}/lib/libzmq.so        # [linux]
    - test -f ${PREFIX}/lib/libzmq.dylib     # [osx]
    - test -f ${PREFIX}/share/cmake/ZeroMQ/ZeroMQConfig.cmake
    - test -f ${PREFIX}/share/cmake/ZeroMQ/ZeroMQConfigVersion.cmake

about:
  home: http://zeromq.org
  license: LGPL 3
  summary: A high-performance asynchronous messaging library.

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - SylvainCorlay
    - JohanMabille
