# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "E3QvO1N/mzMyFb+oTZgSBZRr/EHFKd3fm+654NxPBQ1NzH4LbZVXGES+BhSAbRD6FpK34e73iU5XzI1bNK+s+xhMvbB88WG+QklzZOi5WS0b6krYtmzy0dUGad3jjTQ0KYkZ+GBW8Ex+krRkNQrbxBYpZ3+MyA6d+c7pqIAv9E72Yl6SAkdM3vCjxpfsPYxLGAewhFfJ9LMjDUZWXIgH2uNR75dQg9xiVvGkPDFMAUwe2lzdyK2TwmJKuU49ydH5JB0+qYo8q2QsZ77QM4TaIZmt4Pbv3VneSW+jGpiaqtY5r/IXBVVh3WUNOK8LOpcKg1woOuoBblbcXLGruflG9wne7Dr9DawXJ/LUP64WULjlrLN496kbB8Bk/afoCotGokPy2YAMaOSsGk1nReWq72ozGpMSA04u3oTFLfGijOG+7c07orkDN5U49+o/ZlwEMtP5OEucGMKU+gYVxQlbCxo53Covb5jIbomVNrKzhUuoPvo+Q+Ju6CMm4SSVWF2LgH35dktCrsvzJe3vqhidKed8Ch2pMV7Pjo9W1DD4iPqacaowj4QYpRzgw2/9IMIn5Q2EZkVEHFF+0iFGy7l2AKj5L7JdpS4DTu1X40g1h5v7rWJ1AnvinEWYfKUq7w/cNmNo0aEKdEgmUlbFAlODgPjJhNUlmh2grs9EPamb5ew="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
